name:                c0ffee
version:             0.1.0.0
github:              "mitsuji/c0ffee"
license:             BSD3
author:              "Takamasa Mitsuji"
maintainer:          "tkms@mitsuji.org"
copyright:           "2020 Takamasa Mitsuji"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mitsuji/c0ffee#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring

library:
  source-dirs: src

executables:
  c0ffee-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c0ffee

tests:
  c0ffee-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c0ffee
